# Generated by Django 3.2.7 on 2021-09-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='invalid', max_length=50)),
                ('password', models.CharField(default='invalid', max_length=64)),
                ('email', models.EmailField(default='invalid@invalid.invalid', max_length=250)),
                ('accountActive', models.BooleanField(default=False)),
                ('challenges_solved', models.IntegerField(default=0)),
            ],
        ),
    ]
