# Generated by Django 3.2.7 on 2021-09-21 01:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chalsSolvedName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='none', max_length=100), null=True, size=None),
        ),
    ]
