# Generated by Django 3.2.7 on 2021-09-22 14:50

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20210921_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengeName', models.CharField(max_length=50, null=True)),
                ('challengeType', models.CharField(max_length=50, null=True)),
                ('solves', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('comments', jsonfield.fields.JSONField(null=True)),
                ('difficulty', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
