# Generated by Django 3.2.7 on 2021-09-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='flag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
