# Generated by Django 3.2.7 on 2021-09-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_challenges_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='challengeName',
            new_name='challenge_name',
        ),
        migrations.RenameField(
            model_name='challenges',
            old_name='challengeType',
            new_name='challenge_type',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='chalsSolvedName',
            new_name='chals_solved_name',
        ),
    ]
