# Generated by Django 3.2.7 on 2021-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_challenges_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='challenge_location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
