# Generated by Django 3.2.7 on 2021-10-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_challenges_challenge_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeDevs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_author', models.TextField(null=True)),
                ('challenge_name', models.TextField(null=True)),
                ('challenge_flag', models.TextField(null=True)),
                ('challenge_difficulty', models.CharField(max_length=20, null=True)),
                ('challenge_description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='attack_attempts',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_banned',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_challenge_dev',
            field=models.BooleanField(null=True),
        ),
    ]
