# Generated by Django 3.2.7 on 2021-10-19 10:24

import django.contrib.postgres.fields
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_auto_20211008_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=jsonfield.fields.JSONField(null=True), null=True, size=None),
        ),
    ]
