# Generated by Django 3.2.7 on 2021-10-21 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0011_auto_20211021_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='liked_challenges',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=100), default=[], size=None),
        ),
    ]
