# Generated by Django 3.2.7 on 2021-10-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0014_auto_20211021_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('timing', models.DateTimeField(null=True)),
                ('eventData', models.TextField(null=True)),
            ],
        ),
    ]
