# Generated by Django 3.2.7 on 2021-10-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0015_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='timing',
            field=models.TextField(null=True),
        ),
    ]
