# Generated by Django 3.2.7 on 2021-10-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0016_alter_events_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
