# Generated by Django 3.2.7 on 2021-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challengename', models.CharField(default='invalid', max_length=50)),
                ('username', models.CharField(default='invalid', max_length=20)),
                ('password', models.CharField(default='invalid', max_length=64)),
                ('flag', models.CharField(default='invalid', max_length=100)),
            ],
        ),
    ]
