# Generated by Django 3.2.7 on 2021-09-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenges',
        ),
        migrations.DeleteModel(
            name='WebChallenges',
        ),
    ]
