# Generated by Django 3.2.7 on 2021-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_notes_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
